// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Kx2-LBhmbjp0dxrKdTXaaH-8UdBLeqQ',
    appId: '1:569091665840:web:8964053f17b06a7facb075',
    messagingSenderId: '569091665840',
    projectId: 'fujin-634db',
    authDomain: 'fujin-634db.firebaseapp.com',
    storageBucket: 'fujin-634db.firebasestorage.app',
    measurementId: 'G-74KSDN7ZTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFM5iTkalrjqoGZ_k1c4031KUM5NnvfY',
    appId: '1:569091665840:android:e7e0d3c6b224820eacb075',
    messagingSenderId: '569091665840',
    projectId: 'fujin-634db',
    storageBucket: 'fujin-634db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcKgwaQv_gdYL-dUtJcusU3poInmYE7XM',
    appId: '1:569091665840:ios:c112475b12d77560acb075',
    messagingSenderId: '569091665840',
    projectId: 'fujin-634db',
    storageBucket: 'fujin-634db.firebasestorage.app',
    iosClientId: '569091665840-975nv1vg80449nchvbmkg62cee80lers.apps.googleusercontent.com',
    iosBundleId: 'com.example.wcmFujinMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcKgwaQv_gdYL-dUtJcusU3poInmYE7XM',
    appId: '1:569091665840:ios:c112475b12d77560acb075',
    messagingSenderId: '569091665840',
    projectId: 'fujin-634db',
    storageBucket: 'fujin-634db.firebasestorage.app',
    iosClientId: '569091665840-975nv1vg80449nchvbmkg62cee80lers.apps.googleusercontent.com',
    iosBundleId: 'com.example.wcmFujinMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Kx2-LBhmbjp0dxrKdTXaaH-8UdBLeqQ',
    appId: '1:569091665840:web:6ce1ba767e854ee9acb075',
    messagingSenderId: '569091665840',
    projectId: 'fujin-634db',
    authDomain: 'fujin-634db.firebaseapp.com',
    storageBucket: 'fujin-634db.firebasestorage.app',
    measurementId: 'G-KFGGB16B8Y',
  );
}
